name: 🔧 Install / Update / Uninstall Issue
description: If you have any issue during the installation, update or uninstall
title: '[Install / Update / Uninstall Issue]: '
labels: ['Install / Update / Uninstall Issue']
body:
  - type: markdown
    attributes:
      value: '🦜 Thanks for taking the time to fill out this issue!'
  - type: markdown
    attributes:
      value: 'Please first check if the issue is listed into issues.'
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see and give a screenshot if it's applicable.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      value: '1. '
  - type: markdown
    attributes:
      value: '## Install Environment'
  - type: input
    id: version
    attributes:
      label: Toutui version
      description: Do not put 'Latest version', please put the actual version here
      placeholder: 'e.g. v0.1.0-beta'
  - type: dropdown
    id: install-distro
    attributes:
      label: On which OS ?
      options:
        - Arch Linux
        - Ubuntu
        - Debian
        - macOS
        - Other (list in "Additional Notes" box)
  - type: dropdown
    id: install-method
    attributes:
      label: Which install, update method?
      options:
        - Easy installation (option 1, binary)
        - Easy installation (option 2, compilation)
        - From source
        - Other (list in "Additional Notes" box)
  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: Error message during the installation
      placeholder: Paste message here
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else you want to add?
